name: Healthy

networks:
  backend:
    driver: bridge

services:
  postgres:
    container_name: healthy_postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    container_name: healthy_pgadmin
    image: dpage/pgadmin4:8.14
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./db/docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "15433:80"
    entrypoint:
      - /bin/sh
      - -c
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: false
      KC_HTTP_PORT: 9090
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    command: start-dev --import-realm
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { int code = ((java.net.HttpURLConnection)java.net.URI.create(args[0]).toURL().openConnection()).getResponseCode(); if(code != 200) { System.err.println(\"HTTP Error: \" + code); System.exit(1); } } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/ready']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  vital_signs_db:
    image: influxdb:latest
    container_name: vital_signs_db
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword123
      DOCKER_INFLUXDB_INIT_ORG: health_monitoring
      DOCKER_INFLUXDB_INIT_BUCKET: vital_signs
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super-secret-auth-token-123
    ports:
      - "8086:8086"
    volumes:
      - vital_signs_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  message_broker:
    image: rabbitmq:4.1-management
    container_name: message_broker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - backend

  config-server:
    container_name: config-server
    build: ../config
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - backend

  eureka-server:
    container_name: eureka-server
    build: ../eureka
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - backend

  gateway:
    container_name: gateway
    build: ../api-gateway
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8080/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  auth:
    image: auth-service:latest
    build: ../auth
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8087/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8087
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  patients:
    image: patient-service:latest
    build: ../patients
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8088/api/v1/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=patient-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8088
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  medical-staff:
    image: medical-staff-service:latest
    build: ../medical-staff
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8082/api/v1/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=medical-staff-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8082
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  vital-signs:
    image: vital-signs-service:latest
    build: ../vital-signs-service
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      vital_signs_db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8084/api/v1/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=vital-signs-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8084
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  integration:
    image: integration-service:latest
    build: ../integration
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8083/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=iot-integration-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8083
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  notification:
    image: notification-service:latest
    build: ../notification
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8085/api/v1/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8085
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  visit:
    image: visit-service:latest
    build: ../visits-service
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://127.0.0.1:8089/api/v1/actuator/health/liveness || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_APPLICATION_NAME=visit-service
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8089
      - EUREKA_INSTANCE_INSTANCEID=$${SPRING_APPLICATION_NAME}:$${random.uuid}

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ["CMD", "loki", "-health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/9080' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      loki:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:9090/-/healthy || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend-web:
    build:
      context: ../../frontend-web
    volumes:
      - ../../frontend-web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend

  ai-worker:
    build: ../machine-learing
    image: healthy-ml-env:latest
    container_name: ml_worker
    restart: always
    networks:
      - backend
    depends_on:
      vital_signs_db:
        condition: service_healthy
      message_broker:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; print(urllib.request.urlopen('http://127.0.0.1:8000/health').read())" ]
      interval: 15s
      timeout: 5s
      retries: 3
    environment:
      - INFLUX_URL=http://vital_signs_db:8086
      - INFLUX_TOKEN=super-secret-auth-token-123
      - INFLUX_ORG=health_monitoring
      - RABBITMQ_URL=amqp://admin:adminpassword@message_broker/
      - MODELS_DIR=/app/models/
    volumes:
      - ../machine-learing/models:/app/models

  ai-trainer:
    image: healthy-ml-env:latest
    container_name: ml_trainer
    command: ["python", "train_lstm_job.py"]
    profiles: ["tools"]
    networks:
      - backend
    depends_on:
      vital_signs_db:
        condition: service_healthy
    environment:
      - INFLUX_URL=http://vital_signs_db:8086
      - INFLUX_TOKEN=super-secret-auth-token-123
      - INFLUX_ORG=health_monitoring
      - RABBITMQ_URL=amqp://admin:adminpassword@message_broker/
    volumes:
      - ../machine-learing/models:/app/models

  simulator:
    build: ../simulator
    image: iot-simulator:latest
    profiles: ["simulation"]
    networks:
      - backend
    environment:
      - API_URL=http://integration:8083/api/v1/integration

volumes:
  postgres:
  pgadmin:
  vital_signs_data: