server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy do backendu (opcjonalne, jeśli frontend strzela bezpośrednio do localhost:8080)
    # Jeśli frontend w przeglądarce ma widzieć backend, lepiej zostawić bezpośrednie strzały
    # lub skonfigurować CORS w Spring Boot.
}